module.exports = async ({github, context}) => {
  const fs = require('fs');
  const reportPath = 'scripts/link_check_report.txt';
  
  if (fs.existsSync(reportPath)) {
    const report = fs.readFileSync(reportPath, 'utf8');
    const brokenSection = report.split('BROKEN LINKS:')[1] || 'See attached report';
    
    const issueTitle = `🔗 Broken Links Detected - ${new Date().toISOString().split('T')[0]}`;
    const issueBody = `## 🔍 Automated Link Check Report
    
**Date**: ${new Date().toISOString()}
**Trigger**: Daily automated check

### 💔 Broken Links Found

\`\`\`
${brokenSection.substring(0, 2000)}
\`\`\`

### 📝 Action Required

Please review these broken links and either:
- ✅ Update to working alternative
- ❌ Remove if service is permanently dead
- 🔄 Keep if temporarily down

### 🤖 Automation Note

This issue was automatically created by the daily link checker workflow.
The full report is available in the workflow artifacts.

---
*Generated by [Link Checker Workflow](https://github.com/${context.repo.owner}/${context.repo.repo}/actions)*`;

    // Check if similar issue already exists (last 7 days)
    const issues = await github.rest.issues.listForRepo({
      owner: context.repo.owner,
      repo: context.repo.repo,
      state: 'open',
      labels: 'automated,broken-links',
      since: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
    });
    
    if (issues.data.length === 0) {
      await github.rest.issues.create({
        owner: context.repo.owner,
        repo: context.repo.repo,
        title: issueTitle,
        body: issueBody,
        labels: ['automated', 'broken-links', 'maintenance']
      });
      console.log('Created new issue for broken links');
    } else {
      console.log('Similar issue already exists, skipping creation');
    }
  }
}
