"""
Stage 2: Playwright Link Verifier
Reads results.json generated by check_links.py and uses a real headless browser
to verify links that were flagged as protected, error, warning, or broken.
This helps bypass WAFs (like Cloudflare) and prevents false positive dead links.
"""

import os
import json
from datetime import datetime, timezone
from playwright.sync_api import sync_playwright

def verify_with_playwright(url):
    """
    Returns True if the URL successfully loads in a headless browser, False otherwise.
    """
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(
                viewport={'width': 1280, 'height': 720},
                user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
            )
            page = context.new_page()
            
            # Wait until DOM is loaded or network is mostly idle
            response = page.goto(url, wait_until='domcontentloaded', timeout=15000)
            
            # Check response status
            if response and response.status < 400:
                # Basic success
                browser.close()
                return True, response.status, "Playwright: Verified working"
                
            # If it's a Cloudflare challenge page, the status might be 403 or 503, 
            # but we can check if the title or content indicates a challenge
            title = page.title().lower()
            try:
                content = page.content().lower()
            except:
                content = ""
            
            cloudflare_indicators = ['just a moment', 'cloudflare', 'attention required', 'security check', 'ddos protection']
            if any(indicator in title or indicator in content for indicator in cloudflare_indicators):
                browser.close()
                return True, response.status if response else 403, "Playwright: Verified working (Cloudflare Challenge)"

            browser.close()
            return False, response.status if response else None, f"Playwright: Failed with HTTP {response.status if response else 'Unknown'}"
            
    except Exception as e:
        return False, None, f"Playwright Exception: {str(e)}"

def save_reports(results, unique_links_count):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # 1. Save main report
    report_path = os.path.join(script_dir, 'link_check_report.txt')
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write("LINK CHECK REPORT (Hybrid Verified)\n")
        f.write("=" * 80 + "\n\n")
        f.write(f"Date: {now}\n")
        f.write(f"Total: {unique_links_count}\n")
        f.write(f"Working: {len(results['working'])}\n")
        f.write(f"Protected: {len(results['protected'])}\n")
        f.write(f"Warnings: {len(results['warning'])}\n")
        f.write(f"Errors: {len(results['error'])}\n")
        f.write(f"Broken: {len(results['broken'])}\n")
        f.write(f"Unknown: {len(results['unknown'])}\n\n")

        if results['broken']:
            f.write("BROKEN LINKS:\n")
            f.write("-" * 80 + "\n")
            for r in sorted(results['broken'], key=lambda x: x['url']):
                f.write(f"\n{r['url']}\n  -> {r['note']}\n")

        if results['error']:
            f.write("\nERROR LINKS:\n")
            f.write("-" * 80 + "\n")
            for r in sorted(results['error'], key=lambda x: x['url']):
                f.write(f"\n{r['url']}\n  -> {r['note']}\n")

        if results['unknown']:
            f.write("\nUNKNOWN LINKS:\n")
            f.write("-" * 80 + "\n")
            for r in sorted(results['unknown'], key=lambda x: x['url']):
                f.write(f"\n{r['url']}\n  -> {r['note']}\n")

        if results['warning']:
            f.write("\nWARNING LINKS:\n")
            f.write("-" * 80 + "\n")
            for r in sorted(results['warning'], key=lambda x: x['url']):
                f.write(f"\n{r['url']}\n  -> {r['note']}\n")
                
    # 2. Save broken URLs list
    broken_list_path = os.path.join(script_dir, 'broken_urls.txt')
    broken_urls = sorted([r['url'] for r in results['broken']])
    with open(broken_list_path, 'w', encoding='utf-8') as f:
        for url in broken_urls:
            f.write(f"{url} | {next((r['note'] for r in results['broken'] if r['url'] == url), '')}\n")

    # 3. Save error URLs list
    error_list_path = os.path.join(script_dir, 'error_urls.txt')
    error_urls = sorted(results['error'], key=lambda x: x['url'])
    with open(error_list_path, 'w', encoding='utf-8') as f:
        for r in error_urls:
            f.write(f"{r['url']} | HTTP {r['status']} | {r['note']}\n")

    # 4. Save warning URLs list
    warning_list_path = os.path.join(script_dir, 'warning_urls.txt')
    warning_urls = sorted(results['warning'], key=lambda x: x['url'])
    with open(warning_list_path, 'w', encoding='utf-8') as f:
        for r in warning_urls:
            status_str = f"HTTP {r['status']}" if r['status'] else "N/A"
            f.write(f"{r['url']} | {status_str} | {r['note']}\n")


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    results_path = os.path.join(script_dir, 'results.json')
    
    if not os.path.exists(results_path):
        print("No results.json found. Please run check_links.py first.")
        return 1
        
    with open(results_path, 'r', encoding='utf-8') as f:
        results = json.load(f)
        
    unique_links_count = sum(len(cat) for cat in results.values())
    
    # We will verify all non-working URLs.
    to_verify = []
    # Optionally exclude 'protected' since check_links.py already knows it's bot protection,
    # but Playwright can give a definitive answer on whether it's truly working.
    for state in ['broken', 'error', 'warning', 'protected', 'unknown']:
        to_verify.extend(results[state])
        
    if not to_verify:
        print("No URLs need Playwright verification.")
        return 0
        
    print(f"Playwright Verification: checking {len(to_verify)} URLs...")
    
    # Process the queue
    for item in to_verify:
        url = item['url']
        old_state = item['state']
        
        print(f"Verifying [{old_state}]: {url}")
        
        is_working, new_status, note = verify_with_playwright(url)
        
        if is_working:
            print(f"  -> Success! Was {old_state}, now working.")
            # Remove from old category
            results[old_state] = [i for i in results[old_state] if i['url'] != url]
            # Add to working (or protected if it's a Cloudflare challenge but verified)
            target_state = 'working' if 'Cloudflare Challenge' not in note else 'protected'
            results[target_state].append({
                'url': url,
                'status': new_status,
                'state': target_state,
                'note': note
            })
        else:
            print(f"  -> Still failing: {note}")
            # Update note
            for i in results[old_state]:
                if i['url'] == url:
                    i['note'] += f" | {note}"
                    break
                    
    print("\nVerification complete. Regenerating reports...")
    save_reports(results, unique_links_count)
    print("Hybrid reports successfully generated.")
    return 0
    
if __name__ == "__main__":
    exit(main())
