import React from "react";
import {
  PawPrint,
  Tv,
  ShieldAlert,
  Bot,
  Brain,
  Cpu,
  Boxes,
  Briefcase,
  Coins,
  Bitcoin,
  BookOpen,
  Calendar,
  Cloud,
  GitPullRequest,
  DollarSign,
  CheckCircle2,
  Palette,
  Code2,
  FileText,
  GraduationCap,
  Mail,
  Film,
  Leaf,
  CalendarDays,
  TrendingUp,
  Utensils,
  Gamepad2,
  Globe2,
  Landmark,
  HeartPulse,
  Wifi,
  UserCheck,
  Music,
  Newspaper,
  Camera,
  FlaskConical,
  Lock,
  ShoppingCart,
  Share2,
  Trophy,
  Car,
  Plane,
  Video,
  CloudSun,
  Layers,
  Sparkles,
  Search,
  Database,
  BarChart3,
  Building,
  KeyRound,
  ShieldCheck,
  Activity,
  Radio,
  Smile,
  Server,
  Link,
  Wrench,
  Compass,
  Phone,
  RadioTower,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  animals: PawPrint,
  anime: Sparkles,
  "anti-malware": ShieldAlert,
  "apify-agents": Bot,
  "apify-ai": Brain,
  "apify-automation": Cpu,
  "apify-business": Briefcase,
  "apify-developer-tools": Code2,
  "apify-ecommerce": ShoppingCart,
  "apify-integrations": Boxes,
  "apify-jobs": UserCheck,
  "apify-lead-generation": Search,
  "apify-mcp-servers": Server,
  "apify-news": Newspaper,
  "apify-open-source": GitPullRequest,
  "apify-other": Boxes,
  "apify-real-estate": Building,
  "apify-seo-tools": BarChart3,
  "apify-social-media": Share2,
  "apify-travel": Plane,
  "apify-videos": Video,
  "authentication-identity": KeyRound,
  "blockchain-web3": Coins,
  books: BookOpen,
  business: Briefcase,
  "calendar-holidays": Calendar,
  "cloud-storage-files": Cloud,
  "continuous-integration": GitPullRequest,
  cryptocurrency: Bitcoin,
  "currency-exchange": DollarSign,
  "data-validation": CheckCircle2,
  "demographic-analysis": BarChart3,
  "design-colors": Palette,
  development: Code2,
  dictionaries: BookOpen,
  "documents-productivity": FileText,
  education: GraduationCap,
  "email-sms": Mail,
  entertainment: Film,
  "environment-climate": Leaf,
  events: CalendarDays,
  finance: TrendingUp,
  "food-drink": Utensils,
  "games-comics": Gamepad2,
  geocoding: Compass,
  "geography-countries": Globe2,
  "government-civic": Landmark,
  health: HeartPulse,
  "iot-smart-devices": Wifi,
  "jobs-career": UserCheck,
  "machine-learning": Brain,
  "math-computation": Activity,
  "memes-fun": Smile,
  "mock-data-testing": Database,
  "monitoring-observability": Activity,
  "museums-art": Palette,
  music: Music,
  news: Newspaper,
  "open-source-projects": GitPullRequest,
  "personality-quotes": Sparkles,
  "phone-telephony": Phone,
  photography: Camera,
  podcasts: Radio,
  "public-data": Database,
  science: FlaskConical,
  "security-validation": ShieldCheck,
  shopping: ShoppingCart,
  social: Share2,
  sports: Trophy,
  "text-analysis-nlp": FileText,
  "tracking-logistics": RadioTower,
  transportation: Car,
  "travel-tourism": Plane,
  "unofficial-community": Boxes,
  "url-shorteners": Link,
  "utilities-tools": Wrench,
  video: Video,
  weather: CloudSun,
};

export function getCategoryIcon(slug: string): LucideIcon {
  return CATEGORY_ICON_MAP[slug] || Layers;
}

export function CategoryIcon({
  slug,
  className = "w-5 h-5",
}: {
  slug: string;
  className?: string;
}) {
  const Icon = getCategoryIcon(slug);
  return <Icon className={className} />;
}
